-- =====================================================================
-- Vio ♡ — COMPLETE DATABASE SETUP (generated by `npm run db:bundle`)
-- Paste everything into Supabase → SQL Editor → Run. Run it ONCE on a
-- new project. Do not edit by hand: edit supabase/migrations instead.
-- =====================================================================

-- Safety first: on a database that already holds Vio ♡ (your photos,
-- memories, messages…) this file stops right here and changes nothing.
do $$
begin
  if to_regclass('public.media') is not null then
    raise exception 'Questo database contiene già Vio ♡: setup.sql è solo per un progetto NUOVO e non è stato eseguito. Per aggiornare usa supabase/update.sql (non cancella niente).';
  end if;
end;
$$;

-- ---------------------------------------------------------------------
-- 20260927000001_schema.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- Viola × Adam — schema
-- Every table lives in `public` and is protected by RLS (see the next
-- migration). Enumerations are plain text + CHECK constraints so they can
-- evolve without painful enum migrations.
-- =====================================================================

create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------------
-- Generic helpers
-- ---------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------
-- Profiles & roles
-- role: admin (Adam) | user (Viola) | pending (anyone else: no access)
-- ---------------------------------------------------------------------
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  role text not null default 'pending' check (role in ('admin', 'user', 'pending')),
  display_name text,
  nickname text,
  onboarded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger profiles_touch before update on public.profiles
  for each row execute function public.touch_updated_at();

-- Role lookups used by every RLS policy. SECURITY DEFINER so they can read
-- profiles without recursing into profiles' own policies.
create or replace function public.app_role()
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select role from public.profiles where id = (select auth.uid());
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((select role = 'admin' from public.profiles where id = (select auth.uid())), false);
$$;

create or replace function public.is_member()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((select role in ('admin', 'user') from public.profiles where id = (select auth.uid())), false);
$$;

-- New auth user -> profile. The role can only be pre-assigned through
-- app_metadata, which only the service role can write (never the client).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  requested text := new.raw_app_meta_data ->> 'role';
begin
  insert into public.profiles (id, role, display_name)
  values (
    new.id,
    case when requested in ('admin', 'user') then requested else 'pending' end,
    coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------
-- App settings (key/value, non-secret configuration)
-- ---------------------------------------------------------------------
create table public.app_settings (
  key text primary key check (key ~ '^[a-z_]{2,40}$'),
  value jsonb not null default '{}'::jsonb,
  is_public boolean not null default true,
  updated_by uuid references auth.users (id) on delete set null,
  updated_at timestamptz not null default now()
);

create trigger app_settings_touch before update on public.app_settings
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------
-- Media library (images + audio in the private `media` bucket)
-- ---------------------------------------------------------------------
create table public.media (
  id uuid primary key default gen_random_uuid(),
  kind text not null default 'image' check (kind in ('image', 'audio')),
  bucket text not null default 'media',
  path text not null unique,
  thumb_path text unique,
  mime text not null,
  size_bytes integer not null default 0 check (size_bytes >= 0),
  width integer,
  height integer,
  duration_seconds numeric,
  title text,
  caption text,
  taken_on date,
  category text,
  tags text[] not null default '{}',
  featured boolean not null default false,
  include_in_random boolean not null default true,
  breathing_enabled boolean not null default false,
  ai_avatar_enabled boolean not null default false,
  contexts text[] not null default '{gallery}',
  visibility text not null default 'shared' check (visibility in ('shared', 'private')),
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index media_kind_idx on public.media (kind, visibility);
create index media_contexts_idx on public.media using gin (contexts);
create trigger media_touch before update on public.media
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------
-- Content
-- ---------------------------------------------------------------------
create table public.dedications (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) <= 200),
  body text not null default '' check (char_length(body) <= 20000),
  category text not null default 'no_reason',
  media_id uuid references public.media (id) on delete set null,
  audio_id uuid references public.media (id) on delete set null,
  signature text,
  pinned boolean not null default false,
  position integer not null default 0,
  is_published boolean not null default true,
  publish_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index dedications_category_idx on public.dedications (category);
create trigger dedications_touch before update on public.dedications
  for each row execute function public.touch_updated_at();

create table public.memories (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) <= 200),
  body text not null default '' check (char_length(body) <= 20000),
  kind text not null default 'moment',
  happened_on date,
  place text,
  media_id uuid references public.media (id) on delete set null,
  is_important boolean not null default false,
  position integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index memories_date_idx on public.memories (happened_on desc nulls last);
create trigger memories_touch before update on public.memories
  for each row execute function public.touch_updated_at();

create table public.comfort_actions (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) <= 200),
  text text not null default '' check (char_length(text) <= 4000),
  category text not null default 'practical',
  duration_seconds integer check (duration_seconds is null or duration_seconds between 0 and 7200),
  icon text,
  media_id uuid references public.media (id) on delete set null,
  sound_id uuid references public.media (id) on delete set null,
  cta_label text,
  cta_action text not null default 'none',
  cta_url text,
  weight integer not null default 5 check (weight between 0 and 100),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger comfort_actions_touch before update on public.comfort_actions
  for each row execute function public.touch_updated_at();

create table public.breathing_presets (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) <= 120),
  description text,
  inhale_seconds numeric not null default 4 check (inhale_seconds between 1 and 20),
  hold_seconds numeric not null default 4 check (hold_seconds between 0 and 30),
  exhale_seconds numeric not null default 6 check (exhale_seconds between 1 and 30),
  hold_after_exhale_seconds numeric not null default 0 check (hold_after_exhale_seconds between 0 and 30),
  rounds integer check (rounds is null or rounds between 1 and 200),
  visual text not null default 'heart',
  show_photos boolean not null default true,
  photo_mode text not null default 'blur_to_clear' check (photo_mode in ('blur_to_clear', 'fade', 'none')),
  texts text[] not null default '{}',
  audio_id uuid references public.media (id) on delete set null,
  is_default boolean not null default false,
  is_active boolean not null default true,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger breathing_presets_touch before update on public.breathing_presets
  for each row execute function public.touch_updated_at();

create table public.breathing_media (
  id uuid primary key default gen_random_uuid(),
  preset_id uuid references public.breathing_presets (id) on delete cascade,
  media_id uuid references public.media (id) on delete cascade,
  text text,
  position integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger breathing_media_touch before update on public.breathing_media
  for each row execute function public.touch_updated_at();

create table public.grounding_exercises (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug ~ '^[a-z0-9-]{2,60}$'),
  title text not null,
  description text,
  icon text,
  steps jsonb not null default '[]'::jsonb check (jsonb_typeof(steps) = 'array'),
  end_text text,
  is_active boolean not null default true,
  position integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger grounding_exercises_touch before update on public.grounding_exercises
  for each row execute function public.touch_updated_at();

create table public.countdowns (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  kind text not null default 'custom',
  target_at timestamptz not null,
  icon text,
  media_id uuid references public.media (id) on delete set null,
  recurring_yearly boolean not null default false,
  show_on_home boolean not null default true,
  position integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger countdowns_touch before update on public.countdowns
  for each row execute function public.touch_updated_at();

create table public.time_capsules (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  teaser text,
  body text not null default '' check (char_length(body) <= 30000),
  media_id uuid references public.media (id) on delete set null,
  unlock_at timestamptz not null,
  opened_at timestamptz,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger time_capsules_touch before update on public.time_capsules
  for each row execute function public.touch_updated_at();

create table public.open_when_cards (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null default '' check (char_length(body) <= 20000),
  media_id uuid references public.media (id) on delete set null,
  audio_id uuid references public.media (id) on delete set null,
  animation text not null default 'hearts',
  cta_action text not null default 'none',
  color text,
  icon text,
  position integer not null default 0,
  opened_count integer not null default 0,
  last_opened_at timestamptz,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger open_when_cards_touch before update on public.open_when_cards
  for each row execute function public.touch_updated_at();

create table public.daily_surprises (
  id uuid primary key default gen_random_uuid(),
  kind text not null default 'phrase',
  title text not null,
  body text,
  media_id uuid references public.media (id) on delete set null,
  action text not null default 'none',
  scheduled_on date,
  weight integer not null default 5 check (weight between 0 and 100),
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger daily_surprises_touch before update on public.daily_surprises
  for each row execute function public.touch_updated_at();

create table public.home_modules (
  id uuid primary key default gen_random_uuid(),
  type text not null default 'action' check (type in ('action', 'widget')),
  action text,
  widget text,
  title text not null,
  subtitle text,
  icon text,
  color text,
  url text,
  size text not null default 'md' check (size in ('sm', 'md', 'lg')),
  position integer not null default 0,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger home_modules_touch before update on public.home_modules
  for each row execute function public.touch_updated_at();

create table public.phrases (
  id uuid primary key default gen_random_uuid(),
  kind text not null,
  text text not null check (char_length(text) <= 1000),
  weight integer not null default 5 check (weight between 0 and 100),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index phrases_kind_idx on public.phrases (kind);
create trigger phrases_touch before update on public.phrases
  for each row execute function public.touch_updated_at();

create table public.quiz_questions (
  id uuid primary key default gen_random_uuid(),
  question text not null,
  options text[] not null check (array_length(options, 1) between 2 and 6),
  correct_index integer not null default 0 check (correct_index >= 0 and correct_index < 6),
  explanation text,
  position integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger quiz_questions_touch before update on public.quiz_questions
  for each row execute function public.touch_updated_at();

create table public.audio_items (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  category text not null default 'voice',
  media_id uuid references public.media (id) on delete cascade,
  position integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger audio_items_touch before update on public.audio_items
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------------
-- Viola's own data
-- ---------------------------------------------------------------------
create table public.messages (
  id uuid primary key default gen_random_uuid(),
  sender_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  body text not null check (char_length(body) between 1 and 5000),
  category text not null default 'thought',
  is_private boolean not null default false,
  read_at timestamptz,
  responded_at timestamptz,
  reply text check (reply is null or char_length(reply) <= 5000),
  created_at timestamptz not null default now()
);
create index messages_sender_idx on public.messages (sender_id, created_at desc);

create table public.journal_entries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  title text check (title is null or char_length(title) <= 200),
  body text not null check (char_length(body) between 1 and 20000),
  mood smallint check (mood is null or mood between 1 and 5),
  visibility text not null default 'private' check (visibility in ('private', 'shared')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index journal_user_idx on public.journal_entries (user_id, created_at desc);
create trigger journal_entries_touch before update on public.journal_entries
  for each row execute function public.touch_updated_at();

create table public.mood_entries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  mood smallint check (mood is null or mood between 1 and 5),
  note text check (note is null or char_length(note) <= 2000),
  shared boolean not null default true,
  created_at timestamptz not null default now()
);
create index mood_user_idx on public.mood_entries (user_id, created_at desc);

-- "Ho bisogno di Adam"
create table public.adam_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  message text check (message is null or char_length(message) <= 2000),
  status text not null default 'new' check (status in ('new', 'seen', 'responded', 'closed')),
  response text check (response is null or char_length(response) <= 2000),
  notified_channels text[] not null default '{}',
  notification_ok boolean not null default false,
  seen_at timestamptz,
  responded_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now()
);
create index adam_requests_status_idx on public.adam_requests (status, created_at desc);

create table public.activity_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  type text not null check (type ~ '^[a-z0-9_]{2,60}$'),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index activity_events_idx on public.activity_events (created_at desc);

-- ---------------------------------------------------------------------
-- Notifications
-- ---------------------------------------------------------------------
create table public.notification_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  last_used_at timestamptz
);

create table public.notification_events (
  id uuid primary key default gen_random_uuid(),
  kind text not null,
  request_id uuid references public.adam_requests (id) on delete cascade,
  message_id uuid references public.messages (id) on delete cascade,
  channel text not null check (channel in ('telegram', 'webpush', 'whatsapp', 'none')),
  status text not null check (status in ('sent', 'failed', 'skipped', 'not_configured')),
  detail text,
  created_at timestamptz not null default now()
);
create index notification_events_idx on public.notification_events (created_at desc);

-- ---------------------------------------------------------------------
-- Adam AI
-- ---------------------------------------------------------------------
create table public.ai_conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  scope text not null default 'viola' check (scope in ('viola', 'copilot')),
  mode text not null default 'general' check (mode in ('general', 'personal', 'comfort')),
  title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index ai_conversations_user_idx on public.ai_conversations (user_id, updated_at desc);
create trigger ai_conversations_touch before update on public.ai_conversations
  for each row execute function public.touch_updated_at();

create table public.ai_messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.ai_conversations (id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users (id) on delete cascade,
  role text not null check (role in ('user', 'model', 'note')),
  content text not null default '' check (char_length(content) <= 40000),
  actions jsonb not null default '[]'::jsonb,
  status text not null default 'ok' check (status in ('ok', 'error', 'stopped')),
  input_tokens integer,
  output_tokens integer,
  created_at timestamptz not null default now()
);
create index ai_messages_conv_idx on public.ai_messages (conversation_id, created_at);
create index ai_messages_user_idx on public.ai_messages (user_id, created_at desc);

create table public.ai_memory (
  id uuid primary key default gen_random_uuid(),
  category text not null default 'fact',
  key text not null check (char_length(key) <= 200),
  value text not null check (char_length(value) <= 4000),
  enabled boolean not null default true,
  visible_to_viola boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger ai_memory_touch before update on public.ai_memory
  for each row execute function public.touch_updated_at();

create table public.ai_tool_logs (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid references public.ai_conversations (id) on delete set null,
  user_id uuid references auth.users (id) on delete set null,
  scope text not null check (scope in ('viola', 'copilot')),
  tool text not null,
  args jsonb not null default '{}'::jsonb,
  result jsonb,
  success boolean not null default false,
  status text not null default 'executed' check (status in ('executed', 'pending', 'confirmed', 'rejected', 'failed')),
  confirmed_at timestamptz,
  created_at timestamptz not null default now()
);
create index ai_tool_logs_idx on public.ai_tool_logs (created_at desc);

create table public.ai_usage_daily (
  day date not null,
  user_id uuid not null references auth.users (id) on delete cascade,
  scope text not null check (scope in ('viola', 'copilot')),
  requests integer not null default 0,
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  primary key (day, user_id, scope)
);

-- ---------------------------------------------------------------------
-- Audit
-- ---------------------------------------------------------------------
create table public.admin_audit_logs (
  id uuid primary key default gen_random_uuid(),
  admin_id uuid references auth.users (id) on delete set null,
  action text not null,
  target_table text,
  target_id text,
  before jsonb,
  after jsonb,
  created_at timestamptz not null default now()
);
create index admin_audit_logs_idx on public.admin_audit_logs (created_at desc);

-- ---------------------------------------------------------------------
-- 20260927000002_rls.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- Viola × Adam — Row Level Security, grants and RPCs
--
-- Principles
--   * anon (not logged in) can read NOTHING.
--   * "member" = admin (Adam) or user (Viola). Pending accounts see nothing.
--   * Viola reads published content + her own data.
--   * Private journal entries / unshared moods are invisible to the admin.
--   * Adam (admin) manages content. No "allow all" policies anywhere.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Grants (defence in depth on top of RLS)
-- ---------------------------------------------------------------------
revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke execute on all functions in schema public from anon, public;
alter default privileges in schema public revoke all on tables from anon;
alter default privileges in schema public revoke execute on functions from anon, public;

grant usage on schema public to authenticated, service_role;
grant select, insert, update, delete on all tables in schema public to authenticated;

-- The server-side service role (notifications, settings, cron) must work even
-- on projects where new tables are not auto-exposed to the Data API.
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
grant execute on all functions in schema public to service_role;
alter default privileges in schema public grant all on tables to service_role;
alter default privileges in schema public grant execute on functions to service_role;

-- Tables the client must never write to directly (server / RPC only)
revoke insert, update, delete on public.notification_events from authenticated;
revoke insert, update, delete on public.ai_usage_daily from authenticated;
revoke update, delete on public.admin_audit_logs from authenticated;

-- profiles: users may only touch harmless columns (never `role`)
revoke insert, update, delete on public.profiles from authenticated;
grant update (display_name, nickname, onboarded_at) on public.profiles to authenticated;

-- messages: Viola writes body/category/privacy; Adam writes read/reply state
revoke insert, update on public.messages from authenticated;
grant insert (body, category, is_private) on public.messages to authenticated;
grant update (read_at, responded_at, reply) on public.messages to authenticated;

-- adam_requests: Viola only writes the message; Adam manages the status
revoke insert, update on public.adam_requests from authenticated;
grant insert (message) on public.adam_requests to authenticated;
grant update (status, response, seen_at, responded_at, closed_at) on public.adam_requests to authenticated;

-- open_when_cards / time_capsules counters are only changed via RPC
-- (admins still have full write access through the policies below)

grant execute on function public.app_role() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_member() to authenticated;

-- ---------------------------------------------------------------------
-- Enable RLS on every public table
-- ---------------------------------------------------------------------
do $$
declare
  t record;
begin
  for t in select tablename from pg_tables where schemaname = 'public' loop
    execute format('alter table public.%I enable row level security', t.tablename);
  end loop;
end;
$$;

-- ---------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------
create policy profiles_select on public.profiles for select to authenticated
  using (id = (select auth.uid()) or (select public.is_admin()));
create policy profiles_update_self on public.profiles for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

-- ---------------------------------------------------------------------
-- app_settings
-- ---------------------------------------------------------------------
create policy app_settings_select on public.app_settings for select to authenticated
  using ((select public.is_admin()) or (is_public and (select public.is_member())));
create policy app_settings_admin_insert on public.app_settings for insert to authenticated
  with check ((select public.is_admin()));
create policy app_settings_admin_update on public.app_settings for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy app_settings_admin_delete on public.app_settings for delete to authenticated
  using ((select public.is_admin()));

-- ---------------------------------------------------------------------
-- Admin-managed content: generated policies
--   read_rule : what a member (Viola) may read
--   admins can always read and write everything in these tables
-- ---------------------------------------------------------------------
do $$
declare
  spec record;
begin
  for spec in
    select * from (values
      ('media',               'visibility = ''shared'''),
      ('dedications',         'is_published and (publish_at is null or publish_at <= now())'),
      ('memories',            'is_published'),
      ('comfort_actions',     'is_active'),
      ('breathing_presets',   'is_active'),
      ('breathing_media',     'is_active'),
      ('grounding_exercises', 'is_active'),
      ('countdowns',          'is_published'),
      ('time_capsules',       'is_published and unlock_at <= now()'),
      ('open_when_cards',     'is_published'),
      ('daily_surprises',     'is_published and (scheduled_on is null or scheduled_on <= (now() at time zone ''Europe/Rome'')::date)'),
      ('home_modules',        'is_enabled'),
      ('phrases',             'is_active'),
      ('quiz_questions',      'is_active'),
      ('audio_items',         'is_published'),
      ('ai_memory',           'enabled and visible_to_viola')
    ) as v(tbl, read_rule)
  loop
    execute format(
      'create policy %I on public.%I for select to authenticated using ((select public.is_admin()) or ((select public.is_member()) and (%s)))',
      spec.tbl || '_select', spec.tbl, spec.read_rule);
    execute format(
      'create policy %I on public.%I for insert to authenticated with check ((select public.is_admin()))',
      spec.tbl || '_admin_insert', spec.tbl);
    execute format(
      'create policy %I on public.%I for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()))',
      spec.tbl || '_admin_update', spec.tbl);
    execute format(
      'create policy %I on public.%I for delete to authenticated using ((select public.is_admin()))',
      spec.tbl || '_admin_delete', spec.tbl);
  end loop;
end;
$$;

-- ---------------------------------------------------------------------
-- messages (Viola -> Adam)
-- ---------------------------------------------------------------------
create policy messages_select on public.messages for select to authenticated
  using (sender_id = (select auth.uid()) or (select public.is_admin()));
create policy messages_insert on public.messages for insert to authenticated
  with check (sender_id = (select auth.uid()) and (select public.is_member()));
create policy messages_admin_update on public.messages for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy messages_delete on public.messages for delete to authenticated
  using (sender_id = (select auth.uid()) or (select public.is_admin()));

-- ---------------------------------------------------------------------
-- journal_entries — private by default, admin sees only shared ones
-- ---------------------------------------------------------------------
create policy journal_select on public.journal_entries for select to authenticated
  using (user_id = (select auth.uid()) or ((select public.is_admin()) and visibility = 'shared'));
create policy journal_insert on public.journal_entries for insert to authenticated
  with check (user_id = (select auth.uid()) and (select public.is_member()));
create policy journal_update on public.journal_entries for update to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy journal_delete on public.journal_entries for delete to authenticated
  using (user_id = (select auth.uid()));

-- ---------------------------------------------------------------------
-- mood_entries — admin sees only shared ones
-- ---------------------------------------------------------------------
create policy mood_select on public.mood_entries for select to authenticated
  using (user_id = (select auth.uid()) or ((select public.is_admin()) and shared));
create policy mood_insert on public.mood_entries for insert to authenticated
  with check (user_id = (select auth.uid()) and (select public.is_member()));
create policy mood_update on public.mood_entries for update to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy mood_delete on public.mood_entries for delete to authenticated
  using (user_id = (select auth.uid()));

-- ---------------------------------------------------------------------
-- adam_requests ("Ho bisogno di Adam")
-- ---------------------------------------------------------------------
create policy adam_requests_select on public.adam_requests for select to authenticated
  using (user_id = (select auth.uid()) or (select public.is_admin()));
create policy adam_requests_insert on public.adam_requests for insert to authenticated
  with check (user_id = (select auth.uid()) and (select public.is_member()));
create policy adam_requests_admin_update on public.adam_requests for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy adam_requests_delete on public.adam_requests for delete to authenticated
  using (user_id = (select auth.uid()) or (select public.is_admin()));

-- ---------------------------------------------------------------------
-- activity_events
-- ---------------------------------------------------------------------
create policy activity_select on public.activity_events for select to authenticated
  using (user_id = (select auth.uid()) or (select public.is_admin()));
create policy activity_insert on public.activity_events for insert to authenticated
  with check (user_id = (select auth.uid()) and (select public.is_member()));
create policy activity_delete on public.activity_events for delete to authenticated
  using (user_id = (select auth.uid()) or (select public.is_admin()));

-- ---------------------------------------------------------------------
-- notification_subscriptions (own only) / notification_events (admin read)
-- ---------------------------------------------------------------------
create policy push_subs_select on public.notification_subscriptions for select to authenticated
  using (user_id = (select auth.uid()));
create policy push_subs_insert on public.notification_subscriptions for insert to authenticated
  with check (user_id = (select auth.uid()) and (select public.is_member()));
create policy push_subs_update on public.notification_subscriptions for update to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy push_subs_delete on public.notification_subscriptions for delete to authenticated
  using (user_id = (select auth.uid()));

create policy notification_events_select on public.notification_events for select to authenticated
  using ((select public.is_admin()));

-- ---------------------------------------------------------------------
-- AI conversations / messages (strictly own)
-- ---------------------------------------------------------------------
create policy ai_conv_select on public.ai_conversations for select to authenticated
  using (user_id = (select auth.uid()));
create policy ai_conv_insert on public.ai_conversations for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and (select public.is_member())
    and (scope = 'viola' or (select public.is_admin()))
  );
create policy ai_conv_update on public.ai_conversations for update to authenticated
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()) and (scope = 'viola' or (select public.is_admin())));
create policy ai_conv_delete on public.ai_conversations for delete to authenticated
  using (user_id = (select auth.uid()));

create policy ai_msg_select on public.ai_messages for select to authenticated
  using (user_id = (select auth.uid()));
create policy ai_msg_insert on public.ai_messages for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and exists (
      select 1 from public.ai_conversations c
      where c.id = conversation_id and c.user_id = (select auth.uid())
    )
  );
create policy ai_msg_update on public.ai_messages for update to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy ai_msg_delete on public.ai_messages for delete to authenticated
  using (user_id = (select auth.uid()));

-- ---------------------------------------------------------------------
-- AI tool logs / usage / audit
-- ---------------------------------------------------------------------
create policy ai_tool_logs_select on public.ai_tool_logs for select to authenticated
  using ((select public.is_admin()));
create policy ai_tool_logs_insert on public.ai_tool_logs for insert to authenticated
  with check (user_id = (select auth.uid()) and (select public.is_member()) and (scope = 'viola' or (select public.is_admin())));
create policy ai_tool_logs_admin_update on public.ai_tool_logs for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));

create policy ai_usage_select on public.ai_usage_daily for select to authenticated
  using (user_id = (select auth.uid()) or (select public.is_admin()));

create policy audit_select on public.admin_audit_logs for select to authenticated
  using ((select public.is_admin()));
create policy audit_insert on public.admin_audit_logs for insert to authenticated
  with check ((select public.is_admin()) and admin_id = (select auth.uid()));

-- =====================================================================
-- RPCs
-- =====================================================================

-- Time capsules: list without leaking the body of locked letters
create or replace function public.list_time_capsules()
returns table (
  id uuid,
  title text,
  teaser text,
  unlock_at timestamptz,
  is_unlocked boolean,
  opened_at timestamptz,
  media_id uuid
)
language sql
stable
security definer
set search_path = ''
as $$
  select c.id, c.title, c.teaser, c.unlock_at,
         c.unlock_at <= now() as is_unlocked,
         c.opened_at,
         case when c.unlock_at <= now() then c.media_id else null end
  from public.time_capsules c
  where c.is_published and (select public.is_member())
  order by c.unlock_at asc;
$$;

create or replace function public.mark_capsule_opened(capsule_id uuid)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.time_capsules
     set opened_at = coalesce(opened_at, now())
   where id = capsule_id
     and is_published
     and unlock_at <= now()
     and (select public.is_member());
$$;

create or replace function public.mark_open_when_opened(card_id uuid)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.open_when_cards
     set opened_count = opened_count + 1,
         last_opened_at = now()
   where id = card_id
     and is_published
     and (select public.is_member());
$$;

-- AI usage counters: members can only increment their own counters
create or replace function public.increment_ai_usage(
  p_scope text,
  p_requests integer,
  p_input_tokens integer,
  p_output_tokens integer
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not (select public.is_member()) then
    raise exception 'not allowed';
  end if;
  if p_scope not in ('viola', 'copilot') or (p_scope = 'copilot' and not (select public.is_admin())) then
    raise exception 'invalid scope';
  end if;
  if p_requests < 0 or p_input_tokens < 0 or p_output_tokens < 0
     or p_requests > 20 or p_input_tokens > 2000000 or p_output_tokens > 200000 then
    raise exception 'invalid usage values';
  end if;

  insert into public.ai_usage_daily as u (day, user_id, scope, requests, input_tokens, output_tokens)
  values ((now() at time zone 'Europe/Rome')::date, (select auth.uid()), p_scope, p_requests, p_input_tokens, p_output_tokens)
  on conflict (day, user_id, scope) do update
    set requests = u.requests + excluded.requests,
        input_tokens = u.input_tokens + excluded.input_tokens,
        output_tokens = u.output_tokens + excluded.output_tokens;
end;
$$;

-- Cost control numbers for the admin dashboard
create or replace function public.admin_usage_stats()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  if not (select public.is_admin()) then
    raise exception 'not allowed';
  end if;
  select jsonb_build_object(
    'db_bytes', pg_database_size(current_database()),
    'media_bytes', coalesce((select sum(size_bytes) from public.media), 0),
    'media_count', (select count(*) from public.media),
    'notifications_month', (
      select coalesce(jsonb_object_agg(channel, n), '{}'::jsonb) from (
        select channel, count(*) as n from public.notification_events
        where created_at >= date_trunc('month', now()) and status = 'sent'
        group by channel
      ) s
    )
  ) into result;
  return result;
end;
$$;

grant execute on function public.list_time_capsules() to authenticated;
grant execute on function public.mark_capsule_opened(uuid) to authenticated;
grant execute on function public.mark_open_when_opened(uuid) to authenticated;
grant execute on function public.increment_ai_usage(text, integer, integer, integer) to authenticated;
grant execute on function public.admin_usage_stats() to authenticated;

-- ---------------------------------------------------------------------
-- 20260927000003_storage.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- Viola × Adam — private storage bucket for photos and audio
--   * bucket is PRIVATE: files are served only through short-lived
--     signed URLs created for logged-in members.
--   * size + MIME are enforced by the bucket itself, and again by the app.
-- =====================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'media',
  'media',
  false,
  10485760, -- 10 MB
  array[
    'image/jpeg', 'image/png', 'image/webp',
    'audio/mpeg', 'audio/mp4', 'audio/x-m4a', 'audio/aac', 'audio/ogg', 'audio/wav', 'audio/webm'
  ]
)
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- Members can read a file only if it belongs to a shared media record.
create policy "media read shared" on storage.objects for select to authenticated
  using (
    bucket_id = 'media'
    and (
      (select public.is_admin())
      or (
        (select public.is_member())
        and exists (
          select 1 from public.media m
          where (m.path = storage.objects.name or m.thumb_path = storage.objects.name)
            and m.visibility = 'shared'
        )
      )
    )
  );

create policy "media admin insert" on storage.objects for insert to authenticated
  with check (bucket_id = 'media' and (select public.is_admin()));

create policy "media admin update" on storage.objects for update to authenticated
  using (bucket_id = 'media' and (select public.is_admin()))
  with check (bucket_id = 'media' and (select public.is_admin()));

create policy "media admin delete" on storage.objects for delete to authenticated
  using (bucket_id = 'media' and (select public.is_admin()));

-- ---------------------------------------------------------------------
-- 20260928000001_hardening.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- Vio ♡ — hardening (safe to run more than once)
--
-- Postgres grants EXECUTE on every new function to PUBLIC, and a
-- per-schema "alter default privileges" cannot take that back. So the RPCs
-- created in 20260927000002 were callable by anon (they returned nothing
-- or raised "not allowed", but anon must not reach them at all).
-- =====================================================================

revoke execute on all functions in schema public from public, anon;

grant execute on function
  public.app_role(),
  public.is_admin(),
  public.is_member(),
  public.list_time_capsules(),
  public.mark_capsule_opened(uuid),
  public.mark_open_when_opened(uuid),
  public.increment_ai_usage(text, integer, integer, integer),
  public.admin_usage_stats()
to authenticated;

-- ---------------------------------------------------------------------
-- 20260928000002_privacy.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- Vio ♡ — Viola decides whether Adam sees her activity (safe to re-run)
--
-- Until now every "breathing completed / fear flow / game played" event was
-- visible to the admin. Viola can now switch that off from "La tua privacy".
-- Default stays on (same behaviour as before), and the page explains it.
-- =====================================================================

alter table public.profiles add column if not exists share_activity boolean not null default true;

-- She may change only this switch (still never `role`).
grant update (share_activity) on public.profiles to authenticated;

-- ---------------------------------------------------------------------
-- 20260928000003_hearts.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- Vio ♡ — "Cuore a distanza" (safe to run more than once)
--
-- One tap = "I'm thinking of you". Viola sends a heart, Adam sees it (and
-- gets a gentle, rate-limited notification) and can send one back.
-- Only the two members can see or send hearts.
-- =====================================================================

create table if not exists public.hearts (
  id uuid primary key default gen_random_uuid(),
  from_user uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  seen_at timestamptz
);
create index if not exists hearts_created_idx on public.hearts (created_at desc);

alter table public.hearts enable row level security;

revoke all on public.hearts from anon;
grant select, insert, delete on public.hearts to authenticated;
grant update (seen_at) on public.hearts to authenticated;
grant all on public.hearts to service_role;

drop policy if exists hearts_select on public.hearts;
drop policy if exists hearts_insert on public.hearts;
drop policy if exists hearts_mark_seen on public.hearts;
drop policy if exists hearts_delete_own on public.hearts;

-- a two-person exchange: both members see both directions
create policy hearts_select on public.hearts for select to authenticated
  using ((select public.is_member()));
-- you can only send hearts as yourself
create policy hearts_insert on public.hearts for insert to authenticated
  with check (from_user = (select auth.uid()) and (select public.is_member()));
-- you can only mark as seen the hearts you RECEIVED (column grant: seen_at only)
create policy hearts_mark_seen on public.hearts for update to authenticated
  using ((select public.is_member()) and from_user <> (select auth.uid()))
  with check ((select public.is_member()) and from_user <> (select auth.uid()));
-- and delete only your own (privacy: "cancella i miei dati")
create policy hearts_delete_own on public.hearts for delete to authenticated
  using (from_user = (select auth.uid()));

-- ---------------------------------------------------------------------
-- 20260929000001_readiness.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- Vio ♡ — "Completa Vio ♡" checklist (safe to run more than once)
--
-- Almost every task is derived from the data that already exists. This
-- table only stores what the database cannot know: things Adam checked by
-- hand ("installed on Viola's phone", "offline tested") or optional tasks
-- marked as not needed. Admin only.
-- =====================================================================

create table if not exists public.readiness_checks (
  task_id text primary key check (task_id ~ '^[a-z0-9-]{2,60}$'),
  state text not null default 'done' check (state in ('done', 'skipped')),
  done_at timestamptz not null default now(),
  done_by uuid default auth.uid() references auth.users (id) on delete set null
);

alter table public.readiness_checks enable row level security;

revoke all on public.readiness_checks from anon;
grant select, insert, update, delete on public.readiness_checks to authenticated;
grant all on public.readiness_checks to service_role;

drop policy if exists readiness_admin_select on public.readiness_checks;
drop policy if exists readiness_admin_insert on public.readiness_checks;
drop policy if exists readiness_admin_update on public.readiness_checks;
drop policy if exists readiness_admin_delete on public.readiness_checks;

create policy readiness_admin_select on public.readiness_checks for select to authenticated
  using ((select public.is_admin()));
create policy readiness_admin_insert on public.readiness_checks for insert to authenticated
  with check ((select public.is_admin()));
create policy readiness_admin_update on public.readiness_checks for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy readiness_admin_delete on public.readiness_checks for delete to authenticated
  using ((select public.is_admin()));

-- ---------------------------------------------------------------------
-- 20260930000001_photos.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- Vio ♡ — photos: place, subject position and batch editing
-- (safe to run more than once)
--
-- * media.place  — where the photo was taken (shown under the photo)
-- * media.focus  — which part to keep visible when a frame must crop the
--                  photo (centre / top / bottom / left / right)
-- * admin_batch_update_media  — edits many photos in ONE statement:
--   only the fields present in `patch` change, everything else is left
--   exactly as it was. Runs with the caller's rights (RLS applies) and
--   refuses anyone who is not the admin.
-- * admin_restore_media — "Annulla": puts back the values saved before a
--   batch, only on photos nobody touched after it.
-- =====================================================================

alter table public.media add column if not exists place text;
alter table public.media add column if not exists focus text not null default 'center';

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'media_place_len') then
    alter table public.media add constraint media_place_len check (place is null or char_length(place) <= 120);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'media_focus_check') then
    alter table public.media add constraint media_focus_check check (focus in ('center', 'top', 'bottom', 'left', 'right'));
  end if;
end;
$$;

-- ---------------------------------------------------------------------
-- Batch update
-- patch keys (all optional; a missing key = "non modificare"):
--   category, taken_on, place, caption  (text / date; "" or null = empty)
--   visibility, focus                    (text, checked by the table)
--   featured, include_in_random          (boolean)
--   tags_add, tags_remove, contexts_add, contexts_remove (text arrays)
-- Returns, for every photo really updated, its previous values.
-- ---------------------------------------------------------------------
create or replace function public.admin_batch_update_media(media_ids uuid[], patch jsonb)
returns table (id uuid, previous jsonb, updated_at timestamptz)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  allowed constant text[] := array[
    'category', 'taken_on', 'place', 'caption', 'visibility', 'focus', 'featured', 'include_in_random',
    'tags_add', 'tags_remove', 'contexts_add', 'contexts_remove'
  ];
  tags_add text[] := coalesce(array(select jsonb_array_elements_text(patch -> 'tags_add')), '{}');
  tags_remove text[] := coalesce(array(select jsonb_array_elements_text(patch -> 'tags_remove')), '{}');
  ctx_add text[] := coalesce(array(select jsonb_array_elements_text(patch -> 'contexts_add')), '{}');
  ctx_remove text[] := coalesce(array(select jsonb_array_elements_text(patch -> 'contexts_remove')), '{}');
begin
  if not (select public.is_admin()) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  if coalesce(cardinality(media_ids), 0) = 0 or cardinality(media_ids) > 1000 then
    raise exception 'select between 1 and 1000 photos' using errcode = '22023';
  end if;
  if jsonb_typeof(patch) is distinct from 'object' or patch = '{}'::jsonb
     or exists (select 1 from jsonb_object_keys(patch) k where k <> all (allowed)) then
    raise exception 'invalid patch' using errcode = '22023';
  end if;

  return query
  with prev as (
    select m.id, m.category, m.taken_on, m.place, m.caption, m.visibility, m.focus, m.featured,
           m.include_in_random, m.tags, m.contexts, m.breathing_enabled, m.ai_avatar_enabled,
           case when patch ? 'contexts_add' or patch ? 'contexts_remove'
                then array(select distinct c from unnest(m.contexts || ctx_add) c where c <> all (ctx_remove) order by c)
                else m.contexts end as next_contexts
    from public.media m
    where m.id = any (media_ids)
    for update
  )
  update public.media m set
    category = case when patch ? 'category' then nullif(btrim(patch ->> 'category'), '') else m.category end,
    taken_on = case when patch ? 'taken_on' then nullif(patch ->> 'taken_on', '')::date else m.taken_on end,
    place = case when patch ? 'place' then nullif(btrim(patch ->> 'place'), '') else m.place end,
    caption = case when patch ? 'caption' then nullif(btrim(patch ->> 'caption'), '') else m.caption end,
    visibility = case when patch ? 'visibility' then patch ->> 'visibility' else m.visibility end,
    focus = case when patch ? 'focus' then patch ->> 'focus' else m.focus end,
    featured = case when patch ? 'featured' then (patch ->> 'featured')::boolean else m.featured end,
    include_in_random = case when patch ? 'include_in_random' then (patch ->> 'include_in_random')::boolean else m.include_in_random end,
    tags = case when patch ? 'tags_add' or patch ? 'tags_remove'
                then array(select distinct t from unnest(m.tags || tags_add) t where t <> all (tags_remove) order by t)
                else m.tags end,
    contexts = prev.next_contexts,
    -- flags always follow the contexts (same rule as the single editor)
    breathing_enabled = case when patch ? 'contexts_add' or patch ? 'contexts_remove' then 'breathing' = any (prev.next_contexts) else m.breathing_enabled end,
    ai_avatar_enabled = case when patch ? 'contexts_add' or patch ? 'contexts_remove' then 'adam_ai' = any (prev.next_contexts) else m.ai_avatar_enabled end
  from prev
  where m.id = prev.id
  returning m.id,
    jsonb_build_object(
      'category', prev.category, 'taken_on', prev.taken_on, 'place', prev.place, 'caption', prev.caption,
      'visibility', prev.visibility, 'focus', prev.focus, 'featured', prev.featured,
      'include_in_random', prev.include_in_random, 'tags', to_jsonb(prev.tags), 'contexts', to_jsonb(prev.contexts),
      'breathing_enabled', prev.breathing_enabled, 'ai_avatar_enabled', prev.ai_avatar_enabled
    ),
    m.updated_at;
end;
$$;

-- ---------------------------------------------------------------------
-- Undo a batch: `snapshot` = [{ id, <field>: <previous value>, ... }].
-- Only photos still exactly as the batch left them (updated_at unchanged)
-- are restored; the others were edited meanwhile and are left alone.
-- ---------------------------------------------------------------------
create or replace function public.admin_restore_media(snapshot jsonb, batch_updated_at timestamptz)
returns setof uuid
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if not (select public.is_admin()) then
    raise exception 'not allowed' using errcode = '42501';
  end if;
  if jsonb_typeof(snapshot) is distinct from 'array' or jsonb_array_length(snapshot) > 1000 then
    raise exception 'invalid snapshot' using errcode = '22023';
  end if;

  return query
  update public.media m set
    category = case when s ? 'category' then s ->> 'category' else m.category end,
    taken_on = case when s ? 'taken_on' then (s ->> 'taken_on')::date else m.taken_on end,
    place = case when s ? 'place' then s ->> 'place' else m.place end,
    caption = case when s ? 'caption' then s ->> 'caption' else m.caption end,
    visibility = case when s ? 'visibility' then s ->> 'visibility' else m.visibility end,
    focus = case when s ? 'focus' then s ->> 'focus' else m.focus end,
    featured = case when s ? 'featured' then (s ->> 'featured')::boolean else m.featured end,
    include_in_random = case when s ? 'include_in_random' then (s ->> 'include_in_random')::boolean else m.include_in_random end,
    tags = case when s ? 'tags' then array(select jsonb_array_elements_text(s -> 'tags')) else m.tags end,
    contexts = case when s ? 'contexts' then array(select jsonb_array_elements_text(s -> 'contexts')) else m.contexts end,
    breathing_enabled = case when s ? 'breathing_enabled' then (s ->> 'breathing_enabled')::boolean else m.breathing_enabled end,
    ai_avatar_enabled = case when s ? 'ai_avatar_enabled' then (s ->> 'ai_avatar_enabled')::boolean else m.ai_avatar_enabled end
  from jsonb_array_elements(snapshot) s
  where m.id = (s ->> 'id')::uuid
    and m.updated_at = batch_updated_at
  returning m.id;
end;
$$;

revoke execute on function public.admin_batch_update_media(uuid[], jsonb) from public, anon;
revoke execute on function public.admin_restore_media(jsonb, timestamptz) from public, anon;
grant execute on function public.admin_batch_update_media(uuid[], jsonb) to authenticated;
grant execute on function public.admin_restore_media(jsonb, timestamptz) to authenticated;

-- ---------------------------------------------------------------------
-- seed.sql (starter content)
-- ---------------------------------------------------------------------
-- =====================================================================
-- Viola × Adam — starter content (all editable from the admin dashboard)
-- Safe to run more than once: each block only fills EMPTY tables.
-- Memories and quiz questions are created as DRAFTS (not visible to
-- Viola) because only Adam knows the real ones.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Home modules
-- ---------------------------------------------------------------------
do $$ begin
if not exists (select 1 from public.home_modules) then
  insert into public.home_modules (type, widget, action, title, subtitle, icon, color, size, position) values
    ('widget', 'help_now',       null, 'Aiutami adesso', 'Ti propongo una cosa da fare, subito.', 'sparkles', 'wine', 'lg', 10),
    ('widget', 'mood',           null, 'Come ti senti?', null, 'smile', 'blush', 'lg', 20),
    ('action', null, 'calm',         'Ho bisogno di calmarmi', 'Un posto morbido dove rallentare', 'flower', 'lilac', 'md', 30),
    ('action', null, 'breathe',      'Ho bisogno di respirare', 'Respira con me', 'wind', 'peach', 'md', 40),
    ('action', null, 'fear',         'Ho paura', 'Facciamo una cosa alla volta', 'shield-heart', 'wine', 'md', 50),
    ('action', null, 'need_adam',    'Ho bisogno di Adam', 'Gli arriva subito un avviso', 'heart-handshake', 'red', 'md', 60),
    ('action', null, 'distract',     'Voglio distrarmi', 'Giochi e piccole cose', 'gamepad', 'lilac', 'md', 70),
    ('action', null, 'talk',         'Voglio parlare', 'Scrivimi o parla con Adam AI', 'message-heart', 'blush', 'md', 80),
    ('action', null, 'see_adam',     'Voglio vedere Adam', 'Una foto, subito', 'camera', 'peach', 'md', 90),
    ('action', null, 'memories',     'Voglio ricordarmi di noi', 'Le nostre cose', 'book-heart', 'cream', 'md', 100),
    ('action', null, 'smile',        'Voglio sorridere', 'Una cosa leggera', 'laugh', 'peach', 'md', 110),
    ('action', null, 'ai_chat',      'Chatta con Adam AI', 'Puoi chiedermi qualsiasi cosa', 'bot-heart', 'wine', 'md', 120),
    ('action', null, 'surprise',     'Sorprendimi', 'Non sai cosa uscirà', 'gift', 'red', 'md', 130),
    ('widget', 'daily_surprise', null, 'Una cosa per te ♡', null, 'gift', 'blush', 'lg', 140),
    ('widget', 'countdown',      null, 'Manca poco', null, 'hourglass', 'lilac', 'lg', 150),
    ('widget', 'distance',       null, 'Torino ↔ Rosolina', null, 'map-pin', 'cream', 'lg', 160);
end if;
end $$;

-- ---------------------------------------------------------------------
-- Phrases
-- ---------------------------------------------------------------------
do $$ begin
if not exists (select 1 from public.phrases) then
  insert into public.phrases (kind, text) values
    ('home', 'Respira. Non devi risolvere tutto adesso.'),
    ('home', 'Eccomi.'),
    ('home', 'Un passo alla volta.'),
    ('home', 'Ti ho lasciato questo piccolo posto.'),
    ('home', 'Qui puoi rallentare.'),
    ('home', 'Oggi basta anche solo esserci.'),
    ('home', 'Non devi essere forte per forza, qui.'),
    ('home', 'Ci sono, anche quando non mi vedi.'),

    ('good_morning', 'Buongiorno Vio ♡ Oggi si va un passo alla volta.'),
    ('good_morning', 'Buongiorno amore. Il primo pensiero di oggi era per te.'),
    ('good_morning', 'Sveglia, principessa del letto. Il mondo ti aspetta, ma può aspettare anche cinque minuti.'),
    ('good_morning', 'Buongiorno ♡ Qualsiasi cosa succeda oggi, stasera sarai ancora la mia persona preferita.'),

    ('mission', 'Bevi un bicchiere d''acqua appena puoi.'),
    ('mission', 'Apri la finestra e fai tre respiri d''aria fresca.'),
    ('mission', 'Mandami una foto del tuo cielo di oggi.'),
    ('mission', 'Scegli una canzone che ti mette di buon umore e ascoltala tutta.'),
    ('mission', 'Fai colazione con calma, anche solo cinque minuti.'),
    ('mission', 'Scrivi una cosa bella che vuoi che succeda oggi.'),

    ('good_night', 'Buonanotte Vio ♡ Hai fatto abbastanza per oggi.'),
    ('good_night', 'Chiudi gli occhi. Domani è un altro giorno, e io ci sarò.'),
    ('good_night', 'Lascia qui i pensieri pesanti. Per stanotte li tengo io.'),
    ('good_night', 'Sogna qualcosa di bello. Magari anche me.'),

    ('question', 'Qual è il ricordo più bello che abbiamo insieme?'),
    ('question', 'Dove vorresti andare con me la prossima volta?'),
    ('question', 'Cosa ti ha fatto sorridere oggi?'),
    ('question', 'Qual è la canzone che ti fa pensare a noi?'),
    ('question', 'Come sarebbe la nostra giornata perfetta?'),
    ('question', 'Qual è una cosa piccola che ti rende felice?'),
    ('question', 'Che film guarderemmo stasera sul divano?'),
    ('question', 'Cosa vorresti che facessimo insieme almeno una volta nella vita?'),

    ('roulette', 'Mandami un vocale di 10 secondi ♡'),
    ('roulette', 'Scegli tu il film della prossima serata insieme'),
    ('roulette', 'Scrivi tre cose che ti piacciono di te'),
    ('roulette', 'Fai una foto a qualcosa di bello e mandamela'),
    ('roulette', 'Inventa il nostro prossimo appuntamento'),
    ('roulette', 'Balla la tua canzone preferita per un minuto'),
    ('roulette', 'Chiamami e raccontami una cosa bella della tua giornata'),
    ('roulette', 'Abbraccia un cuscino per venti secondi, vale come mio'),

    ('hug', 'Chiudi gli occhi un secondo.'),
    ('hug', 'Immagina che ti stia abbracciando.'),
    ('hug', 'Stretta stretta. Non ti lascio.'),
    ('hug', 'Sono qui.'),

    ('breathing', 'Respira con me.'),
    ('breathing', 'Eccomi.'),
    ('breathing', 'Un respiro alla volta.'),
    ('breathing', 'Sono qui con te.'),
    ('breathing', 'Piano piano, va tutto bene.'),

    ('smile', 'Lo sapevi che le lontre marine si tengono per la zampa mentre dormono, per non allontanarsi? Un po'' come noi ♡'),
    ('smile', 'Scommetto che adesso stai sorridendo. Ho vinto io.'),
    ('smile', 'Un gruppo di fenicotteri si chiama "flamboyance". Tu da sola sei già una flamboyance.'),
    ('smile', 'Questa app contiene il 100% di amore e lo 0% di conservanti.'),
    ('smile', 'Le mucche hanno una migliore amica. Io ho te, quindi batto le mucche.'),
    ('smile', 'Se fossi un gatto passerei tutte e sette le vite con te.'),

    ('calm_end', 'Brava. Un passo alla volta. ♡'),
    ('calm_end', 'Ce l''hai fatta. Sono fiero di te. ♡'),

    ('da_adam', 'Da Adam ♡'),
    ('da_adam', 'Adam ha lasciato qualcosa per te.'),
    ('da_adam', 'Adam ha preparato questa sorpresa.');
end if;
end $$;

-- ---------------------------------------------------------------------
-- Dedications (10)
-- ---------------------------------------------------------------------
do $$ begin
if not exists (select 1 from public.dedications) then
  insert into public.dedications (title, body, category, position) values
    ('Quando sei triste',
     E'Vio, se stai leggendo questa è perché oggi pesa un po'' di più.\n\nNon devi far finta di stare bene. Puoi essere triste, puoi piangere, puoi stare sotto le coperte. Io non me ne vado.\n\nLa tristezza passa, anche quando sembra di no. E quando passa, io sarò ancora qui.',
     'sad', 10),
    ('Una cosa che non ti dico abbastanza',
     E'Sei una delle cose più belle che mi siano mai successe.\n\nNon per quello che fai, ma per come sei: per come ridi, per come ti preoccupi per gli altri, per come riesci a rendere speciale anche una giornata normale.',
     'love', 20),
    ('Quando hai paura',
     E'Ok. Respira.\n\nLa paura è rumorosa, ma non ha sempre ragione. Non devi risolvere tutto adesso: basta il prossimo respiro, poi quello dopo.\n\nSe vuoi, scrivimi. Anche solo "ci sei?". Io ci sono.',
     'fear', 30),
    ('Quando ti senti sola',
     E'Anche se siamo lontani, non sei sola.\n\nOgni volta che apri questa app, è come se aprissi una porta su casa nostra. L''ho costruita pezzo per pezzo pensando a te.',
     'lonely', 40),
    ('Quando ti manco',
     E'Mi manchi anche tu. Tanto.\n\nConta i giorni con me: ogni giorno che passa è un giorno in meno alla prossima volta che ti abbraccio davvero.',
     'miss_me', 50),
    ('Per farti sorridere',
     E'Piccola lista di cose che mi fanno sorridere:\n\n- la tua voce quando sei appena sveglia\n- quando ridi per una cosa stupida e non riesci a smettere\n- tu, in generale\n\nOra tocca a te sorridere ♡',
     'smile', 60),
    ('Senza nessun motivo',
     E'Nessun motivo speciale.\n\nVolevo solo ricordarti che ti amo. Oggi, adesso, mentre leggi.',
     'no_reason', 70),
    ('Quando hai bisogno di amore',
     E'Ecco una dose di amore, da prendere tutta in una volta:\n\nSei amata. Sei importante. Sei abbastanza. Anche nei giorni storti. Soprattutto nei giorni storti.',
     'love', 80),
    ('Se oggi è stata una giornata no',
     E'Le giornate no esistono, e non sono colpa tua.\n\nStasera fai una cosa gentile per te: una doccia calda, una tisana, una serie che ti piace. Domani ricominciamo, insieme.',
     'sad', 90),
    ('Promemoria',
     E'Promemoria ufficiale, firmato e timbrato:\n\nqualunque cosa succeda, sono dalla tua parte.',
     'no_reason', 100);
end if;
end $$;

-- ---------------------------------------------------------------------
-- Comfort actions (20) for the Random Comfort Engine
-- ---------------------------------------------------------------------
do $$ begin
if not exists (select 1 from public.comfort_actions) then
  insert into public.comfort_actions (title, text, category, duration_seconds, icon, cta_label, cta_action, weight) values
    ('Fai 10 respiri lenti', 'Inspira dal naso, espira piano dalla bocca. Contali uno per uno.', 'breathing', 90, 'wind', 'Respira con me', 'breathe', 9),
    ('Respira con il cuore', 'Segui il cuore che si allarga e si stringe. Solo quello.', 'breathing', 120, 'heart', 'Inizia', 'breathe', 7),
    ('Trova 5 cose blu', 'Guardati intorno e trova cinque cose blu. Dille a voce bassa, una alla volta.', 'grounding', 60, 'eye', null, 'none', 8),
    ('Appoggia i piedi a terra', 'Senti il pavimento sotto i piedi. Premi piano. Sei qui, sei al sicuro.', 'grounding', 45, 'footprints', 'Grounding guidato', 'grounding', 8),
    ('Gioca al 5-4-3-2-1', 'Un piccolo gioco con i tuoi sensi per tornare nel presente.', 'grounding', 180, 'hand', 'Iniziamo', '54321', 8),
    ('Bevi lentamente un bicchiere d''acqua', 'Piccoli sorsi. Senti il fresco che scende.', 'sensory', 60, 'glass-water', null, 'none', 7),
    ('Lavati il viso con acqua fresca', 'L''acqua fresca aiuta il corpo a rallentare. Poi asciugati con calma.', 'sensory', 60, 'droplets', null, 'none', 6),
    ('Abbraccia un cuscino', 'Stringilo forte per venti secondi. Vale come un abbraccio mio.', 'sensory', 20, 'heart-handshake', 'Voglio un abbraccio', 'hug', 7),
    ('Apri la finestra', 'Fai entrare un po'' d''aria. Tre respiri profondi guardando fuori.', 'movement', 60, 'sun', null, 'none', 6),
    ('Stirati come un gatto', 'Braccia in alto, poi giù piano. Muovi le spalle, il collo, le mani.', 'movement', 60, 'cat', null, 'none', 5),
    ('Fai due passi', 'Anche solo per la stanza. Conta dieci passi lenti.', 'movement', 120, 'footprints', null, 'none', 5),
    ('Guarda fuori dalla finestra', 'Scegli una cosa lontana e osservala per un minuto: colori, forme, movimenti.', 'distraction', 60, 'eye', null, 'none', 5),
    ('Fai un mini gioco', 'Distrai la mente per due minuti con un gioco leggero.', 'distraction', 120, 'gamepad', 'Gioca', 'games', 7),
    ('Chiedi qualcosa ad Adam AI', 'Una curiosità, una spiegazione, una chiacchiera. Quello che vuoi.', 'distraction', null, 'bot-heart', 'Apri la chat', 'ai_chat', 5),
    ('Scrivimi tutto quello che stai pensando', 'Non serve che abbia senso. Scrivi e basta, io leggo tutto.', 'writing', null, 'pen', 'Scrivi ad Adam', 'write_adam', 8),
    ('Scrivi nel tuo diario', 'Tiralo fuori dalla testa e mettilo sulla carta. Può restare privato.', 'writing', null, 'notebook', 'Apri il diario', 'journal', 5),
    ('Chiamami', 'Se ti va di sentire la mia voce, chiamami.', 'social', null, 'phone', 'Chiama Adam', 'call', 6),
    ('Apri una nostra foto', 'Guarda una foto di noi e ricordati com''era quel momento.', 'romantic', 30, 'camera', 'Fammi vedere noi', 'random_photo', 8),
    ('Leggi una dedica', 'Ho scritto delle cose per te. Aprine una a caso.', 'romantic', 60, 'mail-heart', 'Leggi', 'random_dedication', 8),
    ('Trova qualcosa che ti ricorda Adam', 'Un oggetto, un colore, una canzone. Tienilo vicino per un po''.', 'romantic', 60, 'sparkles', null, 'none', 6);
end if;
end $$;

-- ---------------------------------------------------------------------
-- Breathing presets (5)
-- ---------------------------------------------------------------------
do $$ begin
if not exists (select 1 from public.breathing_presets) then
  insert into public.breathing_presets
    (name, description, inhale_seconds, hold_seconds, exhale_seconds, hold_after_exhale_seconds, rounds, visual, texts, is_default, position) values
    ('Respiro calmo', 'Il classico: inspira 4, trattieni 4, espira 6.', 4, 4, 6, 0, 8, 'heart', '{"Respira con me.","Eccomi.","Un respiro alla volta."}', true, 10),
    ('Respiro lento', 'Respiro regolare, dolce, senza pause.', 5, 0, 5, 0, 10, 'wave', '{"Piano piano.","Sei qui."}', false, 20),
    ('Respiro a quadrato', 'Quattro tempi uguali: aiuta a mettere ordine.', 4, 4, 4, 4, 6, 'flower', '{"Dentro.","Fermo.","Fuori.","Pausa."}', false, 30),
    ('Respiro lungo', 'Espirazione lunga per rilassarsi di più.', 4, 7, 8, 0, 4, 'sphere', '{"Lascia andare."}', false, 40),
    ('Respiro della buonanotte', 'Per prepararsi a dormire.', 4, 2, 8, 0, 6, 'orb', '{"Buonanotte Vio.","Sei al sicuro."}', false, 50);
end if;
end $$;

-- ---------------------------------------------------------------------
-- Grounding exercises
-- ---------------------------------------------------------------------
do $$ begin
if not exists (select 1 from public.grounding_exercises) then
  insert into public.grounding_exercises (slug, title, description, icon, steps, end_text, position) values
    ('54321', '5-4-3-2-1', 'Un gioco con i sensi per tornare qui e ora.', 'hand',
     '[{"title":"5 cose che vedi","text":"Guardati intorno con calma.","count":5,"emoji":"👀"},
       {"title":"4 cose che senti o tocchi","text":"Il tessuto dei vestiti, il telefono, il pavimento...","count":4,"emoji":"🤲"},
       {"title":"3 suoni","text":"Vicini o lontani, anche piccolissimi.","count":3,"emoji":"👂"},
       {"title":"2 odori","text":"Se non ne senti, pensa ai tuoi odori preferiti.","count":2,"emoji":"🌸"},
       {"title":"1 cosa che ti fa sentire al sicuro","text":"Una persona, un posto, un ricordo.","count":1,"emoji":"💗"}]',
     'Sei qui. Va bene così. ♡', 10),
    ('piedi-a-terra', 'Piedi a terra', 'Radicarsi al pavimento, un passo alla volta.', 'footprints',
     '[{"title":"Siediti o resta in piedi","text":"Come stai più comoda."},
       {"title":"Senti i piedi","text":"Appoggiali bene a terra. Senti il peso che scende."},
       {"title":"Premi piano","text":"Spingi leggermente i piedi verso il pavimento per 5 secondi. Poi rilascia."},
       {"title":"Respira","text":"Tre respiri lenti, sentendo il pavimento che ti sostiene."},
       {"title":"Sei qui","text":"Il pavimento c''è. Tu ci sei."}]',
     'Brava. Sei qui, con i piedi per terra. ♡', 20),
    ('mani', 'Le mani', 'Tornare nel corpo attraverso le mani.', 'hand',
     '[{"title":"Strofina le mani","text":"Strofinale per 10 secondi finché diventano calde."},
       {"title":"Appoggiale","text":"Appoggia le mani calde sul petto o sulla pancia."},
       {"title":"Senti il calore","text":"Resta così per tre respiri."},
       {"title":"Apri e chiudi","text":"Apri e chiudi i pugni lentamente, cinque volte."}]',
     'Le tue mani sono qui. Anche tu. ♡', 30),
    ('stanza', 'La stanza', 'Descrivere lo spazio intorno per calmare la mente.', 'home',
     '[{"title":"Dove sei?","text":"Dì a voce bassa dove ti trovi."},
       {"title":"Che ore sono?","text":"Guarda l''ora e il giorno di oggi."},
       {"title":"Tre colori","text":"Trova tre colori diversi nella stanza."},
       {"title":"Una cosa morbida","text":"Tocca qualcosa di morbido e descrivila."}]',
     'Sei qui, adesso. È tutto ciò che conta. ♡', 40);
end if;
end $$;

-- ---------------------------------------------------------------------
-- Open When cards (6)
-- ---------------------------------------------------------------------
do $$ begin
if not exists (select 1 from public.open_when_cards) then
  insert into public.open_when_cards (title, body, animation, cta_action, icon, color, position) values
    ('Aprimi quando ti senti sola',
     E'Non sei sola, Vio.\n\nMagari adesso non sono lì, ma sto pensando a te più spesso di quanto immagini. Se vuoi, premi il bottone qui sotto e scrivimi: rispondo appena posso.',
     'hearts', 'need_adam', 'heart', 'blush', 10),
    ('Aprimi quando ti manco',
     E'Anche tu mi manchi.\n\nChiudi gli occhi e pensa all''ultima volta che ci siamo abbracciati. Ecco: tienilo lì. Il prossimo arriva presto.',
     'stars', 'random_photo', 'moon', 'lilac', 20),
    ('Aprimi quando hai avuto una giornata terribile',
     E'Ok, oggi è andata male. Succede.\n\nNon devi aggiustare niente stasera. Doccia calda, pigiama, qualcosa di buono. Se vuoi raccontarmela, io sono qui ad ascoltare. Domani è un''altra pagina.',
     'petals', 'write_adam', 'cloud-rain', 'peach', 30),
    ('Aprimi quando vuoi sentirti amata',
     E'Sei amata. Non "un po''", non "a volte": sei amata e basta.\n\nPer come sei, anche nei giorni in cui non ti piaci.',
     'hearts', 'random_dedication', 'heart', 'wine', 40),
    ('Aprimi quando non riesci a dormire',
     E'Ciao nottambula.\n\nMetti giù il telefono tra poco, promesso? Prima però facciamo insieme qualche respiro lento. Buonanotte amore mio.',
     'stars', 'breathe', 'moon-star', 'lilac', 50),
    ('Aprimi quando vuoi sorridere',
     E'Pronta? Immagina me che provo a ballare. Male. Molto male.\n\nEcco, lo sapevo che sorridevi ♡',
     'petals', 'smile', 'laugh', 'peach', 60);
end if;
end $$;

-- ---------------------------------------------------------------------
-- Memories (5) — DRAFTS: Adam fills them with our real story
-- ---------------------------------------------------------------------
do $$ begin
if not exists (select 1 from public.memories) then
  insert into public.memories (title, body, kind, is_published, position) values
    ('Il nostro primo appuntamento', 'Scrivi qui com''è andato il vostro primo appuntamento e aggiungi una foto. Poi pubblicalo.', 'date', false, 10),
    ('Il nostro primo viaggio', 'Dove siete andati? Cosa ricordi di più? Aggiungi data, luogo e foto.', 'trip', false, 20),
    ('Il nostro anniversario', 'La data in cui è iniziato tutto.', 'anniversary', false, 30),
    ('Il compleanno di Viola', 'Un ricordo di un suo compleanno insieme.', 'birthday', false, 40),
    ('Il nostro posto', 'Un luogo che per voi è importante.', 'place', false, 50);
end if;
end $$;

-- ---------------------------------------------------------------------
-- Countdown (1) — draft until Adam sets the real date
-- ---------------------------------------------------------------------
do $$ begin
if not exists (select 1 from public.countdowns) then
  insert into public.countdowns (title, description, kind, target_at, icon, is_published, position)
  values ('Il nostro prossimo incontro', 'Ogni giorno è un giorno in meno.', 'meeting', now() + interval '14 days', 'heart', false, 10);
end if;
end $$;

-- ---------------------------------------------------------------------
-- Daily surprises (5)
-- ---------------------------------------------------------------------
do $$ begin
if not exists (select 1 from public.daily_surprises) then
  insert into public.daily_surprises (kind, title, body, action, weight) values
    ('phrase', 'Una cosa vera', 'Oggi, come ieri e come domani: sono dalla tua parte. ♡', 'none', 5),
    ('question', 'Una domanda per te', 'Qual è la cosa più bella che ti è successa questa settimana? Mandamela.', 'write_adam', 5),
    ('exercise', 'Un minuto per te', 'Un minuto di respiro lento, solo per te.', 'breathe', 5),
    ('mini_game', 'Trova il cuore', 'Un piccolo gioco: riesci a trovare il cuore nascosto?', 'game_heart', 5),
    ('surprise', 'Fammi vedere noi', 'Una nostra foto, pescata a caso.', 'random_photo', 5);
end if;
end $$;

-- ---------------------------------------------------------------------
-- Quiz questions — DRAFT templates (only Adam knows the answers)
-- ---------------------------------------------------------------------
do $$ begin
if not exists (select 1 from public.quiz_questions) then
  insert into public.quiz_questions (question, options, correct_index, explanation, is_active, position) values
    ('Qual è il mio cibo preferito?', '{"Pizza","Sushi","Carbonara","Tiramisù"}', 0, 'Modifica questa domanda con la risposta giusta.', false, 10),
    ('Dove ci siamo visti la prima volta?', '{"Opzione A","Opzione B","Opzione C"}', 0, 'Modifica questa domanda con la risposta giusta.', false, 20),
    ('Qual è la mia canzone preferita?', '{"Opzione A","Opzione B","Opzione C"}', 0, 'Modifica questa domanda con la risposta giusta.', false, 30);
end if;
end $$;

-- ---------------------------------------------------------------------
-- AI memory — one safe starter fact (edit freely)
-- ---------------------------------------------------------------------
do $$ begin
if not exists (select 1 from public.ai_memory) then
  insert into public.ai_memory (category, key, value, enabled, visible_to_viola) values
    ('nickname', 'Soprannome', 'Adam chiama Viola "Vio".', true, true);
end if;
end $$;
