-- =====================================================================
-- Vio ♡ — DATABASE UPDATE (generated by `npm run db:bundle`)
-- For projects set up with an older supabase/setup.sql: paste everything
-- into Supabase → SQL Editor → Run. Safe to run more than once.
-- Includes: 20260928000001_hardening.sql, 20260928000002_privacy.sql, 20260928000003_hearts.sql, 20260929000001_readiness.sql
-- =====================================================================

-- ---------------------------------------------------------------------
-- 20260928000001_hardening.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- Vio ♡ — hardening (safe to run more than once)
--
-- Postgres grants EXECUTE on every new function to PUBLIC, and a
-- per-schema "alter default privileges" cannot take that back. So the RPCs
-- created in 20260927000002 were callable by anon (they returned nothing
-- or raised "not allowed", but anon must not reach them at all).
-- =====================================================================

revoke execute on all functions in schema public from public, anon;

grant execute on function
  public.app_role(),
  public.is_admin(),
  public.is_member(),
  public.list_time_capsules(),
  public.mark_capsule_opened(uuid),
  public.mark_open_when_opened(uuid),
  public.increment_ai_usage(text, integer, integer, integer),
  public.admin_usage_stats()
to authenticated;

-- ---------------------------------------------------------------------
-- 20260928000002_privacy.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- Vio ♡ — Viola decides whether Adam sees her activity (safe to re-run)
--
-- Until now every "breathing completed / fear flow / game played" event was
-- visible to the admin. Viola can now switch that off from "La tua privacy".
-- Default stays on (same behaviour as before), and the page explains it.
-- =====================================================================

alter table public.profiles add column if not exists share_activity boolean not null default true;

-- She may change only this switch (still never `role`).
grant update (share_activity) on public.profiles to authenticated;

-- ---------------------------------------------------------------------
-- 20260928000003_hearts.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- Vio ♡ — "Cuore a distanza" (safe to run more than once)
--
-- One tap = "I'm thinking of you". Viola sends a heart, Adam sees it (and
-- gets a gentle, rate-limited notification) and can send one back.
-- Only the two members can see or send hearts.
-- =====================================================================

create table if not exists public.hearts (
  id uuid primary key default gen_random_uuid(),
  from_user uuid not null default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  seen_at timestamptz
);
create index if not exists hearts_created_idx on public.hearts (created_at desc);

alter table public.hearts enable row level security;

revoke all on public.hearts from anon;
grant select, insert, delete on public.hearts to authenticated;
grant update (seen_at) on public.hearts to authenticated;
grant all on public.hearts to service_role;

drop policy if exists hearts_select on public.hearts;
drop policy if exists hearts_insert on public.hearts;
drop policy if exists hearts_mark_seen on public.hearts;
drop policy if exists hearts_delete_own on public.hearts;

-- a two-person exchange: both members see both directions
create policy hearts_select on public.hearts for select to authenticated
  using ((select public.is_member()));
-- you can only send hearts as yourself
create policy hearts_insert on public.hearts for insert to authenticated
  with check (from_user = (select auth.uid()) and (select public.is_member()));
-- you can only mark as seen the hearts you RECEIVED (column grant: seen_at only)
create policy hearts_mark_seen on public.hearts for update to authenticated
  using ((select public.is_member()) and from_user <> (select auth.uid()))
  with check ((select public.is_member()) and from_user <> (select auth.uid()));
-- and delete only your own (privacy: "cancella i miei dati")
create policy hearts_delete_own on public.hearts for delete to authenticated
  using (from_user = (select auth.uid()));

-- ---------------------------------------------------------------------
-- 20260929000001_readiness.sql
-- ---------------------------------------------------------------------
-- =====================================================================
-- Vio ♡ — "Completa Vio ♡" checklist (safe to run more than once)
--
-- Almost every task is derived from the data that already exists. This
-- table only stores what the database cannot know: things Adam checked by
-- hand ("installed on Viola's phone", "offline tested") or optional tasks
-- marked as not needed. Admin only.
-- =====================================================================

create table if not exists public.readiness_checks (
  task_id text primary key check (task_id ~ '^[a-z0-9-]{2,60}$'),
  state text not null default 'done' check (state in ('done', 'skipped')),
  done_at timestamptz not null default now(),
  done_by uuid default auth.uid() references auth.users (id) on delete set null
);

alter table public.readiness_checks enable row level security;

revoke all on public.readiness_checks from anon;
grant select, insert, update, delete on public.readiness_checks to authenticated;
grant all on public.readiness_checks to service_role;

drop policy if exists readiness_admin_select on public.readiness_checks;
drop policy if exists readiness_admin_insert on public.readiness_checks;
drop policy if exists readiness_admin_update on public.readiness_checks;
drop policy if exists readiness_admin_delete on public.readiness_checks;

create policy readiness_admin_select on public.readiness_checks for select to authenticated
  using ((select public.is_admin()));
create policy readiness_admin_insert on public.readiness_checks for insert to authenticated
  with check ((select public.is_admin()));
create policy readiness_admin_update on public.readiness_checks for update to authenticated
  using ((select public.is_admin())) with check ((select public.is_admin()));
create policy readiness_admin_delete on public.readiness_checks for delete to authenticated
  using ((select public.is_admin()));
