import type { FieldDef } from "@/features/admin/resources";
import type { SettingsKey } from "./schema";


// Form definitions for every settings group (labels in Italian for Adam).
export const SETTINGS_FORMS: Partial<Record<SettingsKey, { title: string; description: string; fields: FieldDef[] }>> = {
  general: {
    title: "Generale",
    description: "Nome dell'app, soprannomi, firma e testi principali della home.",
    fields: [
      { name: "appName", label: "Nome dell'app", type: "text", half: true, hint: "Anche il nome della PWA" },
      { name: "shortName", label: "Nome breve (sotto l'icona)", type: "text", half: true, hint: "Max 14 caratteri" },
      { name: "violaName", label: "Nome di Viola", type: "text", half: true },
      { name: "violaNickname", label: "Soprannome", type: "text", half: true },
      { name: "adamName", label: "Il tuo nome", type: "text", half: true },
      { name: "signature", label: "Firma", type: "text", half: true, placeholder: "— Adam ♡" },
      { name: "loginTitle", label: "Titolo della schermata di accesso", type: "text" },
      { name: "loginSubtitle", label: "Sottotitolo accesso", type: "text" },
      { name: "homeGreeting", label: "Saluto in home", type: "text", half: true },
      { name: "homeQuestion", label: "Domanda in home", type: "text", half: true },
      { name: "needsTitle", label: "Titolo della sezione card", type: "text" },
      { name: "showDaAdam", label: "Mostra le firme \"Da Adam ♡\"", type: "boolean" },
      { name: "timezone", label: "Fuso orario", type: "text", hint: "Es. Europe/Rome" },
    ],
  },
  onboarding: {
    title: "Prima apertura",
    description: "Le schermate di benvenuto mostrate una sola volta.",
    fields: [
      { name: "enabled", label: "Mostra il benvenuto al primo accesso", type: "boolean" },
      { name: "slides", label: "Schermate", type: "pairs", max: 6 },
      { name: "cta", label: "Pulsante finale", type: "text" },
    ],
  },
  texts: {
    title: "Testi dell'app",
    description: "Frasi delle esperienze di calma, \"Ho paura\", \"Ho bisogno di Adam\", errori…",
    fields: [
      { name: "calmTitle", label: "Titolo \"Calmati\"", type: "text", half: true },
      { name: "calmEnd", label: "Fine calma", type: "text", half: true },
      { name: "breathingEnd", label: "Fine respirazione", type: "text", half: true },
      { name: "groundingEnd", label: "Fine grounding", type: "text", half: true },
      { name: "fearIntro1", label: "\"Ho paura\" — prima frase", type: "text" },
      { name: "fearIntro2", label: "\"Ho paura\" — seconda frase", type: "text" },
      { name: "fearSteps", label: "\"Ho paura\" — passi", type: "pairs", max: 8, hint: "Il passo con \"respir\" nel titolo mostra il respiro guidato; il penultimo mostra le emozioni; l'ultimo le scelte" },
      { name: "fearFeelings", label: "Emozioni da scegliere", type: "list" },
      { name: "needAdamTitle", label: "Titolo pagina \"Ho bisogno di Adam\"", type: "text", half: true },
      { name: "needAdamButton", label: "Testo del grande pulsante", type: "text", half: true },
      { name: "needAdamPlaceholder", label: "Suggerimento messaggio", type: "text" },
      { name: "needAdamSent", label: "Conferma quando la notifica è arrivata", type: "text" },
      { name: "needAdamFallback", label: "Messaggio se nessuna notifica è partita", type: "text" },
      { name: "hugTitle", label: "Titolo abbraccio", type: "text", half: true },
      { name: "capsuleLocked", label: "Capsula chiusa", type: "text", half: true },
      { name: "capsuleReady", label: "Capsula pronta", type: "text" },
      { name: "errorText", label: "Messaggio di errore", type: "text" },
      { name: "aiOffline", label: "Adam AI offline", type: "text" },
      { name: "aiPause", label: "Adam AI in pausa (limite raggiunto)", type: "text" },
      { name: "safetyNote", label: "Nota di sicurezza", type: "textarea" },
    ],
  },
  contact: {
    title: "Contatti",
    description: "WhatsApp e telefono per il fallback di \"Ho bisogno di Adam\".",
    fields: [
      { name: "whatsappNumber", label: "Numero WhatsApp (solo cifre, con prefisso: 39…)", type: "text", half: true, hint: "Vuoto = usa ADMIN_WHATSAPP_NUMBER" },
      { name: "phoneNumber", label: "Numero di telefono per \"Chiama Adam\"", type: "text", half: true, hint: "Vuoto = stesso di WhatsApp" },
      { name: "whatsappMessages", label: "Messaggi WhatsApp pronti", type: "list" },
      { name: "emergencyNumber", label: "Numero di emergenza", type: "text", half: true },
    ],
  },
  distance: {
    title: "Distanza",
    description: "Le due città, senza GPS, e il countdown del prossimo incontro.",
    fields: [
      { name: "fromName", label: "Città 1", type: "text", half: true },
      { name: "toName", label: "Città 2", type: "text", half: true },
      { name: "fromLat", label: "Città 1 — latitudine", type: "number", step: 0.0001, half: true },
      { name: "fromLng", label: "Città 1 — longitudine", type: "number", step: 0.0001, half: true },
      { name: "toLat", label: "Città 2 — latitudine", type: "number", step: 0.0001, half: true },
      { name: "toLng", label: "Città 2 — longitudine", type: "number", step: 0.0001, half: true },
      { name: "fromLabel", label: "Etichetta città 1 (es. Adam)", type: "text", half: true },
      { name: "toLabel", label: "Etichetta città 2 (es. Viola)", type: "text", half: true },
      { name: "countdownId", label: "Countdown del prossimo incontro", type: "select", options: [] },
      { name: "note", label: "Frase", type: "text" },
    ],
  },
  calm: {
    title: "Calma",
    description: "Comportamento di \"Ho bisogno di calmarmi\".",
    fields: [
      {
        name: "defaultMode",
        label: "All'apertura",
        type: "select",
        options: [
          { value: "choose", label: "Viola sceglie la modalità" },
          { value: "random", label: "Parte una modalità a caso" },
        ],
      },
      { name: "timers", label: "Timer disponibili (secondi, 0 = libero)", type: "numbers", placeholder: "s" },
    ],
  },
  notifications: {
    title: "Preferenze notifiche",
    description: "Come e quando avvisarti.",
    fields: [
      {
        name: "mode",
        label: "Strategia",
        type: "select",
        options: [
          { value: "fallback", label: "Prima Telegram, poi Web Push se Telegram fallisce" },
          { value: "all", label: "Tutti i canali configurati insieme" },
        ],
      },
      { name: "notifyOnMessage", label: "Avvisami quando Viola mi scrive", type: "boolean" },
      { name: "notifyOnSharedJournal", label: "Avvisami quando condivide una pagina di diario", type: "boolean" },
      { name: "notifyOnLowMood", label: "Avvisami se segna un umore basso (😭 o 😔)", type: "boolean" },
      { name: "telegramChatId", label: "Telegram chat ID", type: "text", hint: "Vuoto = usa TELEGRAM_ADMIN_CHAT_ID" },
    ],
  },
  ai_profile: {
    title: "Profilo Adam AI",
    description: "Come si presenta Adam AI a Viola.",
    fields: [
      { name: "avatarMediaId", label: "Foto profilo / avatar", type: "image" },
      { name: "name", label: "Nome", type: "text", half: true },
      { name: "signature", label: "Firma", type: "text", half: true },
      { name: "subtitle", label: "Sottotitolo", type: "text" },
      { name: "bio", label: "Descrizione", type: "textarea" },
      { name: "welcome", label: "Messaggio di benvenuto", type: "textarea" },
      { name: "quickActions", label: "Azioni rapide sopra la chat", type: "list" },
    ],
  },
  ai: {
    title: "Personalità e limiti",
    description: "Tono, personalità, contesto e limiti gratuiti di Adam AI.",
    fields: [
      { name: "enabled", label: "Adam AI attivo", type: "boolean", half: true },
      { name: "copilotEnabled", label: "AI Copilot attivo (admin)", type: "boolean", half: true },
      {
        name: "defaultMode",
        label: "Modalità iniziale",
        type: "select",
        half: true,
        options: [
          { value: "general", label: "General" },
          { value: "personal", label: "Personal" },
          { value: "comfort", label: "Comfort" },
        ],
      },
      {
        name: "verbosity",
        label: "Lunghezza risposte",
        type: "select",
        half: true,
        options: [
          { value: "short", label: "Brevi" },
          { value: "medium", label: "Medie" },
          { value: "long", label: "Lunghe" },
        ],
      },
      { name: "tone", label: "Tono", type: "text" },
      { name: "personality", label: "Personalità", type: "textarea" },
      { name: "language", label: "Lingua", type: "text", half: true },
      { name: "temperature", label: "Creatività (0-2)", type: "number", min: 0, max: 2, step: 0.1, half: true },
      { name: "preferredPhrases", label: "Frasi che ogni tanto può usare", type: "list" },
      { name: "context", label: "Contesto generale (chi siete, cosa sapere)", type: "textarea", hint: "Solo cose vere: l'AI non deve inventare nulla" },
      { name: "restrictions", label: "Cose da NON fare / dire", type: "textarea" },
      { name: "model", label: "Modello Gemini", type: "text", half: true, hint: "Default: gemini-flash-latest" },
      { name: "fallbackModels", label: "Modelli di riserva (solo gratuiti)", type: "list" },
      { name: "dailyMessageLimit", label: "Messaggi al giorno (Viola)", type: "number", min: 0, max: 5000, half: true },
      { name: "perMinuteLimit", label: "Messaggi al minuto", type: "number", min: 1, max: 60, half: true },
      { name: "dailyTokenBudget", label: "Budget token al giorno", type: "number", min: 0, half: true },
      { name: "maxOutputTokens", label: "Token massimi per risposta", type: "number", min: 64, max: 8192, half: true },
      { name: "copilotDailyLimit", label: "Messaggi Copilot al giorno", type: "number", min: 0, max: 5000, half: true },
    ],
  },
  cost: {
    title: "Soglie di costo",
    description: "Limiti del piano gratuito usati per gli avvisi.",
    fields: [
      { name: "dbLimitMb", label: "Database gratuito (MB)", type: "number", half: true },
      { name: "storageLimitMb", label: "Storage gratuito (MB)", type: "number", half: true },
      { name: "warnPercent", label: "Avvisami al (%)", type: "number", min: 10, max: 100, half: true },
    ],
  },
};
